[package]
name = "Sudoku-Solver"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
reqwest = { version = "0.12.20", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
